config/routes.rb
Todos::Application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'homepage'

  resources :sessions, only: [:create]
  resources :todos, only: [:index, :new, :create] do
    collection do
      get :send_todos
    end
    resource :completion, only: [:create]
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  def user=(user)
    self.owner_email = user.email
  end

  def complete?
    completed_at.present?
  end
end

app/models/user.rb
class User
  attr_reader :email

  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(owner_email: email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sign_in(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
  helper_method :current_user
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo = Todo.find(params[:todo_id])
    todo.touch(:completed_at)
    redirect_to todos_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    sign_in(params[:session][:email])
    redirect_to todos_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    @todo.save!
    redirect_to action: :index
  end

  def send_todos
    TodoMailer.
      completed_todos(current_user.email).
      deliver
    redirect_to action: :index
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="welcome">Welcome <%= current_user.email %>!</p>
<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<p data-role="description">Welcome to Todos</p>
<%= form_for :session, url: sessions_path do |form| %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.submit 'Sign in' %>
<% end %>

app/views/todos/index.html.erb
<ul class='todos'>
  <% @todos.each do |todo| %>
    <li class="todo<%= ' completed' if todo.complete? %>">
    <%= todo.description %>
    <%= link_to 'Complete', todo_completion_path(todo.id), method: 'POST' %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add new todo', new_todo_path %>
<%= link_to 'Email completed todos', send_todos_todos_path %>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.submit 'Create todo' %>
<% end %>